theme = "native"

[icons]
name = "awesome6"
[icons.overrides]
# time = ""

[[block]]
block = "time"
interval = 1
format = "%s"

[[block]]
block = "custom"
shell = "dash"
command = "nvidia-i3-status.sh"
interval = 5

[[block]]
block = "speedtest"
interval = 1600
# format = " $ping $speed_down "
format = " {ping} {speed_down} "

[[block]]
block = "custom"
# Barebones shell with no extra formatting
shell = "dash"
# Ping Google's rock solid DNS server
# Print packet loss percentage and total time to send packet(s)
# Send a total of -c=2 packets with a deadline timeout of -W=2 seconds
# -W Time to wait for response
# -t Time to live for each packet
# -i Wait this many seconds between sending each packet
# -c Send this many packets
command = '''ping -W 0.5 -t 250 -i 0.05 -c 10   8.8.8.8   | grep -o "[0-9.]\\+% packet loss, time" | sed "s/ packet loss, time/L/ ; s/ms//"'''
interval = 3

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
ap_format = "{ssid^2}"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+", "lo", "localhost", "loop"]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
format_swap = "{swap_used}"

[[block]]
block = "cpu"
format = "{utilization} {frequency}"
interval = 2

[[block]]
block = "temperature"
interval = 2
collapsed = false
scale = "fahrenheit"
format = "{average}F"

[[block]]
block = "sound"
step_width = 1
on_click = "pavucontrol"

[[block]]
block = "sound"
step_width = 1
device_kind = "source"
on_click = "pavucontrol"

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
on_click = "xkb-switch -n"
format = "{layout} {variant}"
interval = 1

# timezone = "US/Pacific"
# timezone = "US/Mountain"
# timezone = "US/Central"
# timezone = "US/Eastern"
# timezone = "Europe/Paris"
# timezone = "America/Argentina/Buenos_Aires"

[[block]]
block = "time"
interval = 15
timezone = "US/Mountain"
format = "%d %R"

[[block]]
block = "battery"
interval = 30
format = "{percentage} {power}"
device = "BAT1"
missing_format = "?"

[[block]]
block = "battery"
interval = 30
format = "{percentage} {power}"
device = "BAT0"
missing_format = "?"

[[block]]
block = "music"
max_width = 12
marquee_speed = 0.15
marquee_interval = 4
buttons = ["play"]
