[theme]
name = "nord-dark"

[icons]
name = "awesome"
[icons.overrides]
time = ""
cpu = ""

[[block]]
block = "time"
interval = 1
timezone = "UTC"
format = "%s"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents} RAM"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
format = "{utilization} {frequency}"
interval = 1

[[block]]
block = "temperature"
interval = 1
collapsed = false
format = "{average}"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "sound"
device_kind = "source"
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 1
timezone = "UTC"
format = "%H"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %R"

[[block]]
block = "time"
interval = 1
timezone = "US/Mountain"
format = "%H"

[[block]]
block = "time"
interval = 1
timezone = "US/Central"
format = "%H"

[[block]]
block = "time"
interval = 1
timezone = "America/Argentina/Buenos_Aires"
format = "%H"

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
on_click = "xkb-switch -n"
format = "{layout} {variant}"
interval = 1

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
